version: 0.2

phases:
    install:
        runtime-versions:
            python: 3.12
        commands:
            - python -m pip install --upgrade pip
            - python -m pip install pipx
            - PATH=$PATH:/root/.local/bin
            - pipx install poetry ruff
            - poetry config virtualenvs.in-project true
            - poetry install --without dev
    pre_build:
        commands:
            - ruff format --check
            - ruff check
    build:
        commands:
            - mkdir -p dist/lambda-package
            - cp --recursive .venv/lib/python*/site-packages/* dist/lambda-package/
            - cp --recursive src dist/lambda-package/
            - (cd dist/lambda-package; zip -r ../lambda-package-4.zip *)

artifacts:
  files:
    - dist/lambda-package.zip
  discard-paths: yes
  name: lambda-package-$(date +%Y-%m-%d)
